spring:
  application:
    name: command
  profiles:
    active: logging-profile

mongo:
  host: ${BOOKING_SYSTEM_MONGO_HOST}
  port: 27017
  login: ${BOOKING_SYSTEM_MONGO_LOGIN}
  password: ${BOOKING_SYSTEM_MONGO_PASSWORD}
  authDatabase: ${BOOKING_SYSTEM_MONGO_AUTH_DB}
  database: ${BOOKING_SYSTEM_MONGO_DB}

kafka:
  clientId: ${BOOKING_SYSTEM_KAFKA_COMMAND_SERVICE_CLIENT_ID}
  groupId: ${BOOKING_SYSTEM_KAFKA_COMMAND_SERVICE_GROUP_ID}
  bootstrapServers: ${BOOKING_SYSTEM_KAFKA_BOOTSTRAP_SERVERS}

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    com.mongodb: DEBUG
    org.mongodb.driver: DEBUG