spring:
  application:
    name: command
  profiles:
    active: logging-profile

mongo:
  host: localhost
  port: 27017
  login: admin
  password: pass
  authDatabase: admin
  database: booking-service-db

kafka:
  clientId: command-consumer
  hosts: localhost:9092
  groupId: command-consumers

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    com.mongodb: DEBUG
    org.mongodb.driver: DEBUG