services:
  booking-service-mongo:
    image: mongo:8.0.0
    container_name: booking-service-mongo
    hostname: booking-service-mongo
    networks:
      - net
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_ROOT_DATABASE=booking-service-db
    volumes:
      - booking-service-mongo-db-data:/data/db
      - booking-service-mongo-db-config:/data/configdb
  booking-service-mongo-express:
    image: mongo-express
    container_name: booking-service-mongo-express
    restart: always
    networks:
      - net
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=booking-service-mongo
      - ME_CONFIG_MONGODB_PORT=27017

volumes:
  booking-service-mongo-db-data:
  booking-service-mongo-db-config:

networks:
  net: