services:
  booking-system-booking-service:
    build:
      context: .
      dockerfile: ./booking-service/Dockerfile
    image: booking-service:latest
    container_name: booking-system-booking-service
    hostname: booking-system-booking-service
    networks:
      - net
    ports:
      - "8080:8080"
    env_file:
      - .env

  booking-system-query-service:
    build:
      context: .
      dockerfile: ./query-service/Dockerfile
    image: query-service:latest
    container_name: booking-system-query-service
    hostname: booking-system-query-service
    networks:
      - net
    ports:
      - "8081:8080"
    env_file:
      - .env

  booking-system-command-service:
    build:
      context: .
      dockerfile: ./command-service/Dockerfile
    image: command-service:latest
    container_name: booking-system-command-service
    hostname: booking-system-command-service
    networks:
      - net
    env_file:
      - .env

  booking-system-kafka:
    image: apache/kafka:3.8.0
    container_name: booking-system-kafka
    hostname: booking-system-kafka
    networks:
      - net
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: BROKER://0.0.0.0:9092,CONTROLLER://localhost:9093 # Interesting detail, 0.0.0.0 ip must be used
      KAFKA_ADVERTISED_LISTENERS: BROKER://booking-system-kafka:9092,                # to allow clients to connect.
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1         # These 1 values are required to override the defaults which are
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1 # for cluster(more than 1), if defaults are used, there is strange
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1            # behaviour.
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - booking-system-kafka-data:/var/lib/kafka/data
      - booking-system-kafka-secrets:/etc/kafka/secrets
      - booking-system-kafka-config:/mnt/shared/config
  booking-system-mongo:
    image: mongo:8.0.0
    container_name: booking-system-mongo
    hostname: booking-system-mongo
    networks:
      - net
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${BOOKING_SYSTEM_MONGO_LOGIN}
      - MONGO_INITDB_ROOT_PASSWORD=${BOOKING_SYSTEM_MONGO_PASSWORD}
      - MONGO_INITDB_ROOT_DATABASE=${BOOKING_SYSTEM_MONGO_DB}
    volumes:
      - booking-system-mongo-db-data:/data/db
      - booking-system-mongo-db-config:/data/configdb
  booking-system-mongo-express:
    image: mongo-express
    container_name: booking-system-mongo-express
    restart: always
    networks:
      - net
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${BOOKING_SYSTEM_MONGO_LOGIN}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${BOOKING_SYSTEM_MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=${BOOKING_SYSTEM_MONGO_HOST}
      - ME_CONFIG_MONGODB_PORT=27017

volumes:
  booking-system-kafka-data:
  booking-system-kafka-secrets:
  booking-system-kafka-config:
  booking-system-mongo-db-data:
  booking-system-mongo-db-config:

networks:
  net: