spring:
  application:
    name: booking-service

kafka:
  hosts: ${BOOKING_SYSTEM_KAFKA_HOSTS}
  clientId: ${BOOKING_SYSTEM_KAFKA_BOOKING_SERVICE_CLIENT_ID}

query:
  service:
    url: http://${BOOKING_SYSTEM_QUERY_SERVICE_HOST}:8080
