openapi: 3.0.0
info:
  title: Booking API
  description: API for managing bookings.
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /booking/create:
    post:
      summary: Create a new booking.
      requestBody:
        description: The details of the booking to be created.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBookingRequest'
      responses:
        '200':
          description: Booking successfully created.
        '400':
          description: Bad request due to invalid parameters or malformed input.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        '500':
          description: Internal server error due to an unexpected condition.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'

  /booking/delete:
    post:
      summary: Delete an existing booking.
      requestBody:
        description: The details of the booking to be deleted.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteBookingRequest'
      responses:
        '200':
          description: Booking successfully deleted.
        '400':
          description: Bad request due to invalid parameters or malformed input.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        '500':
          description: Internal server error due to an unexpected condition.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'

  /booking/available:
    get:
      summary: Get available time ranges for a service on a specific date.
      parameters:
        - name: date
          in: query
          description: The date to check for available time ranges.
          required: true
          schema:
            type: string
            format: date
        - name: serviceId
          in: query
          description: The ID of the service for which time ranges are being queried.
          required: true
          schema:
            $ref: '#/components/schemas/ObjectId'
        - name: serviceDuration
          in: query
          description: The duration of the service in minutes.
          required: true
          schema:
            type: integer
            format: int32
            minimum: 1
      responses:
        '200':
          description: A list of available time ranges for the service.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TimeRangeResponse'
        '400':
          description: Bad request due to invalid parameters or malformed input.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        '500':
          description: Internal server error due to an unexpected condition.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'

  /booking:
    get:
      summary: Get the booking information for a specific user.
      parameters:
        - name: date
          in: query
          description: The date of the booking.
          required: true
          schema:
            type: string
            format: date
        - name: serviceId
          in: query
          description: The ID of the service for the booking.
          required: true
          schema:
            $ref: '#/components/schemas/ObjectId'
        - name: bookingId
          in: query
          description: The ID of the booking.
          required: true
          schema:
            $ref: '#/components/schemas/ObjectId'
      responses:
        '400':
          description: Bad request due to invalid parameters or malformed input.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        '404':
          description: User booking not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        '500':
          description: Internal server error due to an unexpected condition.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'

  /booking/all:
    get:
      summary: Get all bookings for specified dates, services, and users.
      parameters:
        - name: dates
          in: query
          description: A comma-separated list of dates to fetch bookings for.
          required: true
          schema:
            type: string
            example: "2024-12-01,2024-12-02"
        - name: serviceIds
          in: query
          description: A comma-separated list of service IDs to filter bookings.
          required: true
          schema:
            type: string
            example: "5f8d0d55b4e1c1a6b4f7d4f7,5f8d0d55b4e1c1a6b4f7d4f8"
        - name: userIds
          in: query
          description: A comma-separated list of user IDs to filter bookings.
          required: true
          schema:
            type: string
            example: "5f8d0d55b4e1c1a6b4f7d4f9,5f8d0d55b4e1c1a6b4f7d4fa"
      responses:
        '200':
          description: A list of service bookings.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServiceBookingResponse'
        '400':
          description: Bad request due to invalid parameters or malformed input.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        '500':
          description: Internal server error due to an unexpected condition.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'

components:
  schemas:
    ObjectId:
      type: string
      pattern: "^[a-fA-F0-9]{24}$"  # MongoDB ObjectId format

    CreateBookingRequest:
      type: object
      properties:
        date:
          type: string
          format: date
        serviceId:
          $ref: '#/components/schemas/ObjectId'
        userId:
          $ref: '#/components/schemas/ObjectId'
        start:
          type: integer
        end:
          type: integer
      required:
        - date
        - serviceId
        - userId
        - start
        - end

    DeleteBookingRequest:
      type: object
      properties:
        date:
          type: string
          format: date
        serviceId:
          $ref: '#/components/schemas/ObjectId'
        bookingId:
          $ref: '#/components/schemas/ObjectId'
        userId:
          $ref: '#/components/schemas/ObjectId'
      required:
        - date
        - serviceId
        - bookingId
        - userId

    TimeRangeResponse:
      type: object
      properties:
        start:
          type: integer
        end:
          type: integer

    UserBookingResponse:
      type: object
      properties:
        userId:
          $ref: '#/components/schemas/ObjectId'
        start:
          type: integer
        end:
          type: integer

    ServiceBookingResponse:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/ObjectId'
        date:
          type: string
          format: date
        serviceId:
          $ref: '#/components/schemas/ObjectId'
        bookings:
          type: array
          items:
            $ref: '#/components/schemas/Booking'

    Booking:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/ObjectId'
        userId:
          $ref: '#/components/schemas/ObjectId'
        start:
          type: integer
        end:
          type: integer

    ProblemDetail:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
